packages:
  - apps/*
  - packages/*
  - docs
onlyBuiltDependencies:
  - '@clerk/shared'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - msw
  - sharp
  - unrs-resolver
  - utf-8-validate
  - workerd
