/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MemoryDemoRouteImport } from './routes/memory-demo'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as SignupSsoCallbackRouteImport } from './routes/signup.sso-callback'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as LoginSsoCallbackRouteImport } from './routes/login.sso-callback'
import { Route as LayoutChatIdRouteImport } from './routes/_layout.$chatId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryDemoRoute = MemoryDemoRouteImport.update({
  id: '/memory-demo',
  path: '/memory-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SignupSsoCallbackRoute = SignupSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => SignupRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSsoCallbackRoute = LoginSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => LoginRoute,
} as any)
const LayoutChatIdRoute = LayoutChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/memory': typeof MemoryRoute
  '/memory-demo': typeof MemoryDemoRoute
  '/signup': typeof SignupRouteWithChildren
  '/$chatId': typeof LayoutChatIdRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/memory': typeof MemoryRoute
  '/memory-demo': typeof MemoryDemoRoute
  '/signup': typeof SignupRouteWithChildren
  '/$chatId': typeof LayoutChatIdRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/memory': typeof MemoryRoute
  '/memory-demo': typeof MemoryDemoRoute
  '/signup': typeof SignupRouteWithChildren
  '/_layout/$chatId': typeof LayoutChatIdRoute
  '/login/sso-callback': typeof LoginSsoCallbackRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/signup/sso-callback': typeof SignupSsoCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/memory'
    | '/memory-demo'
    | '/signup'
    | '/$chatId'
    | '/login/sso-callback'
    | '/share/$shareId'
    | '/signup/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/login'
    | '/memory'
    | '/memory-demo'
    | '/signup'
    | '/$chatId'
    | '/login/sso-callback'
    | '/share/$shareId'
    | '/signup/sso-callback'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/admin'
    | '/login'
    | '/memory'
    | '/memory-demo'
    | '/signup'
    | '/_layout/$chatId'
    | '/login/sso-callback'
    | '/share/$shareId'
    | '/signup/sso-callback'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRouteWithChildren
  MemoryRoute: typeof MemoryRoute
  MemoryDemoRoute: typeof MemoryDemoRoute
  SignupRoute: typeof SignupRouteWithChildren
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-demo': {
      id: '/memory-demo'
      path: '/memory-demo'
      fullPath: '/memory-demo'
      preLoaderRoute: typeof MemoryDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/signup/sso-callback': {
      id: '/signup/sso-callback'
      path: '/sso-callback'
      fullPath: '/signup/sso-callback'
      preLoaderRoute: typeof SignupSsoCallbackRouteImport
      parentRoute: typeof SignupRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/sso-callback': {
      id: '/login/sso-callback'
      path: '/sso-callback'
      fullPath: '/login/sso-callback'
      preLoaderRoute: typeof LoginSsoCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_layout/$chatId': {
      id: '/_layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof LayoutChatIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutChatIdRoute: typeof LayoutChatIdRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutChatIdRoute: LayoutChatIdRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface LoginRouteChildren {
  LoginSsoCallbackRoute: typeof LoginSsoCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSsoCallbackRoute: LoginSsoCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupSsoCallbackRoute: typeof SignupSsoCallbackRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSsoCallbackRoute: SignupSsoCallbackRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRouteWithChildren,
  MemoryRoute: MemoryRoute,
  MemoryDemoRoute: MemoryDemoRoute,
  SignupRoute: SignupRouteWithChildren,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
